# Generated by Django 4.0.3 on 2022-04-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='pack_id',
            new_name='pack',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='pack_id',
            new_name='pack',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pack',
            old_name='author_id',
            new_name='author',
        ),
    ]
